name: SpigotPlugin
version: '1.0-SNAPSHOT'
main: me.stierprogrammer.spigotPlugin.SpigotPlugin
api-version: '1.21'
commands:
  sethome:
    description: Set your home location.
    usage: /<command>
  home:
    description: Teleport to your home location.
    usage: /<command>
  homes:
    description: Shows all of your home locations.
    usage: /<command>
  suicide:
    description: Let's you kill yourself.
    usage: /<command>
  godmode:
    description: Gives you god mode
    usage: /<command>