name: SpigotPlugin
version: '1.0-SNAPSHOT'
main: me.stierprogrammer.spigotPlugin.SpigotPlugin
api-version: '1.21'
commands:
  sethome:
    description: Set your home location.
  home:
    description: Teleport to your home location.
  suicide:
    description: Let's you kill yourself.